"use client";

import { useState } from "react";
import { Copy, Check, Download } from "lucide-react";
import type { NarrativeResult } from "@/lib/api";

interface Props {
  result: NarrativeResult;
}

const WEIGHT_COLORS: Record<string, string> = {
  high:   "bg-amber-100 text-amber-800 border-amber-300",
  medium: "bg-sky-100 text-sky-800 border-sky-300",
  low:    "bg-gray-100 text-gray-600 border-gray-300",
};

export default function NarrativeViewer({ result }: Props) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(`${result.headline}\n\n${result.narrative}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable (e.g. non-HTTPS) — silently ignore
    }
  };

  const downloadMarkdown = () => {
    const md = `# ${result.headline}\n\n${result.narrative}\n\n---\n_${result.word_count} words — generated by Narrate-AI_`;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "narrative.md";
    // Must be in the DOM for Firefox to trigger the download
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8">
      {/* Article */}
      <div className="bg-white rounded-2xl border border-gray-200 p-8 shadow-sm">
        <h1 className="text-2xl font-bold text-gray-900 leading-tight mb-6">
          {result.headline}
        </h1>
        <div className="prose prose-gray max-w-none text-gray-700 leading-relaxed whitespace-pre-wrap">
          {result.narrative}
        </div>
        <p className="mt-6 text-xs text-gray-400">{result.word_count} words</p>
      </div>

      {/* Insights panel */}
      {result.insights.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-3">
            Key Insights Driving This Narrative
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {result.insights.map((insight, i) => (
              <div
                key={i}
                className="rounded-xl border border-gray-200 bg-gray-50 p-4 space-y-2"
              >
                <div className="flex items-start justify-between gap-2">
                  <p className="text-sm font-medium text-gray-800 leading-snug">{insight.finding}</p>
                  <span className={`shrink-0 text-xs font-medium px-2 py-0.5 rounded-full border ${WEIGHT_COLORS[insight.emotional_weight] ?? WEIGHT_COLORS.low}`}>
                    {insight.emotional_weight}
                  </span>
                </div>
                <p className="text-xs text-indigo-700 font-mono bg-indigo-50 rounded px-2 py-1">
                  {insight.data_evidence}
                </p>
                <p className="text-xs text-gray-500">{insight.significance}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export actions */}
      <div className="flex gap-3">
        <button
          onClick={copyToClipboard}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700 transition-colors"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 text-green-600" />
              <span className="text-green-600">Copied!</span>
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              Copy to clipboard
            </>
          )}
        </button>
        <button
          onClick={downloadMarkdown}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
        >
          <Download className="w-4 h-4" />
          Download .md
        </button>
      </div>
    </div>
  );
}
