"use client";

import { useState } from "react";
import { Copy, Check, Download } from "lucide-react";
import type { NarrativeResult } from "@/lib/api";

interface Props {
  result: NarrativeResult;
}

const WEIGHT_COLORS: Record<string, string> = {
  high:   "bg-amber-50 text-amber-700 border-amber-200",
  medium: "bg-sky-50 text-sky-700 border-sky-200",
  low:    "bg-gray-100 text-gray-500 border-gray-200",
};

const WEIGHT_LABELS: Record<string, string> = {
  high: "High impact", medium: "Medium", low: "Low",
};

export default function NarrativeViewer({ result }: Props) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(`${result.headline}\n\n${result.narrative}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable — silently ignore
    }
  };

  const downloadMarkdown = () => {
    const md = `# ${result.headline}\n\n${result.narrative}\n\n---\n_${result.word_count} words — generated by Narrate-AI_`;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "narrative.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">

      {/* ── Article card ── */}
      <div className="card overflow-hidden">
        {/* Accent top bar */}
        <div className="h-1 bg-gradient-to-r from-indigo-500 via-violet-500 to-indigo-400" />
        <div className="p-8 sm:p-10">
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 leading-tight mb-1">
            {result.headline}
          </h1>
          <div className="h-px bg-gray-100 my-5" />
          <div className="text-gray-600 leading-[1.8] text-[15px] whitespace-pre-wrap">
            {result.narrative}
          </div>
          <p className="mt-8 text-xs text-gray-300 font-mono">{result.word_count} words</p>
        </div>
      </div>

      {/* ── Insights grid ── */}
      {result.insights.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-3 px-1">
            Key Insights
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {result.insights.map((insight, i) => (
              <div
                key={i}
                className="rounded-xl border border-gray-200 bg-white p-4 space-y-2.5 hover:border-gray-300 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-start gap-2.5">
                    <span className="shrink-0 w-5 h-5 rounded-full bg-indigo-100 text-indigo-600 text-[10px] font-bold flex items-center justify-center mt-0.5">
                      {i + 1}
                    </span>
                    <p className="text-sm font-medium text-gray-800 leading-snug">{insight.finding}</p>
                  </div>
                  <span className={`shrink-0 text-[10px] font-semibold px-2 py-0.5 rounded-full border ${WEIGHT_COLORS[insight.emotional_weight] ?? WEIGHT_COLORS.low}`}>
                    {WEIGHT_LABELS[insight.emotional_weight] ?? insight.emotional_weight}
                  </span>
                </div>
                <p className="text-xs text-indigo-600 font-mono bg-indigo-50 rounded-lg px-2.5 py-1.5 leading-relaxed">
                  {insight.data_evidence}
                </p>
                <p className="text-xs text-gray-400 leading-relaxed">{insight.significance}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Export row ── */}
      <div className="flex gap-2.5">
        <button
          type="button"
          onClick={copyToClipboard}
          className="btn-ghost"
        >
          {copied ? (
            <><Check className="w-4 h-4 text-green-600" /><span className="text-green-600">Copied!</span></>
          ) : (
            <><Copy className="w-4 h-4" />Copy</>
          )}
        </button>
        <button
          type="button"
          onClick={downloadMarkdown}
          className="btn-primary"
        >
          <Download className="w-4 h-4" />
          Download .md
        </button>
      </div>

    </div>
  );
}
